name: PowerShell Script Validation
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install PowerShell
        run: |
          sudo apt-get install -y wget
          wget https://github.com/PowerShell/PowerShell/releases/download/v7.1.0/powershell-7.1.0-linux-x64.tar.gz
          mkdir powershell
          tar -xvf ./powershell-7.1.0-linux-x64.tar.gz -C ./powershell
          sudo mv ./powershell /usr/local/bin/powershell
      - name: Run PowerShell Script
        run: pwsh ./createvm.ps1
