name: PowerShell Script Validation
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up PowerShell
        uses: PowerShell/setup-powershell@v2
        with:
          version: '7.1.0'  # You can change this version if needed

      - name: Run PowerShell Script
        run: pwsh ./createVM.ps1

